mysql:
  base:
    addr: 10.58.150.2
    port: 13306
    user: puppy
    pass: 123456
  database: xgface
redis:
    base:
      addr: localhost
      port: 6379
    max-idle: 1
    idle-timeout: 60
    max-active: 10
    timeout: 10
xgface:
  base:
    addr: 10.58.150.2
    port: 50000
index:
  base:
    addr: 10.58.150.2
    port: 50001
imgbasepath: /home/mechanic/image
faceimgpath: /camera/face/
img_server: http://10.58.150.2/cameraimages